/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sie;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author denis
 */
public class intrebarea extends javax.swing.JPanel {

    /**
     * Creates new form intrebarea
     */
    public intrebarea() {
        initComponents();
    }
    
    boolean mult = false;
    String ras[] = {"-", "-", "-"};
    public intrebarea(int idIntrebare, String continut, String var1, String var2, String var3, int timpIntr, boolean multiplu, int nrIntreb) {
        initComponents();
        nrIntrebare.setText("Intrebarea " + nrIntreb);
        continutIntrebare.setText(continut);
        mult = multiplu;
        
        if(!multiplu){//daca nu are mai multe variante de raspuns       
            //adauga-le intr-un buttonGroup
            buttonGroup.add(optiunea1);
            buttonGroup.add(optiunea2);
            buttonGroup.add(optiunea3);
        } 
                
        optiunea1.setText(var1);
        optiunea2.setText(var2);
        optiunea3.setText(var3);
    }
    
    public String[] getRaspunsuri() {
        return ras;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        nrIntrebare = new javax.swing.JLabel();
        timerIntrebare = new javax.swing.JLabel();
        tipRaspuns = new javax.swing.JPanel();
        optiunea1 = new javax.swing.JRadioButton();
        optiunea2 = new javax.swing.JRadioButton();
        optiunea3 = new javax.swing.JRadioButton();
        continutIntrebare = new javax.swing.JLabel();

        nrIntrebare.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nrIntrebare.setText("Intrebarea ");

        timerIntrebare.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        timerIntrebare.setForeground(new java.awt.Color(255, 51, 51));
        timerIntrebare.setText("00");

        tipRaspuns.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        optiunea1.setText("jRadioButton1");
        optiunea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optiunea1ActionPerformed(evt);
            }
        });

        optiunea2.setText("jRadioButton2");
        optiunea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optiunea2ActionPerformed(evt);
            }
        });

        optiunea3.setText("jRadioButton3");
        optiunea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optiunea3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tipRaspunsLayout = new javax.swing.GroupLayout(tipRaspuns);
        tipRaspuns.setLayout(tipRaspunsLayout);
        tipRaspunsLayout.setHorizontalGroup(
            tipRaspunsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tipRaspunsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(tipRaspunsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optiunea3)
                    .addComponent(optiunea2)
                    .addComponent(optiunea1))
                .addContainerGap(572, Short.MAX_VALUE))
        );
        tipRaspunsLayout.setVerticalGroup(
            tipRaspunsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tipRaspunsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(optiunea1)
                .addGap(34, 34, 34)
                .addComponent(optiunea2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(optiunea3)
                .addGap(21, 21, 21))
        );

        continutIntrebare.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        continutIntrebare.setText("Continut intrebare");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(continutIntrebare)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tipRaspuns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(nrIntrebare)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(timerIntrebare)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nrIntrebare)
                    .addComponent(timerIntrebare))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(continutIntrebare)
                .addGap(18, 18, 18)
                .addComponent(tipRaspuns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void optiunea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optiunea1ActionPerformed
        // TODO add your handling code here:
        if(mult) {
            if(ras[0].equals("-"))
                ras[0] = optiunea1.getText(); 
            else
                ras[0] = "-";
        } else {
            ras[0] = optiunea1.getText();
            ras[1] = "-"; 
            ras[2] = "-"; 
        }
       
    }//GEN-LAST:event_optiunea1ActionPerformed

    private void optiunea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optiunea2ActionPerformed
        // TODO add your handling code here:
        if(mult) {
            if(ras[1].equals("-"))
                ras[1] = optiunea2.getText(); 
            else
                ras[1] = "-";
        } else {
            ras[1] = optiunea2.getText();
            ras[0] = "-"; 
            ras[2] = "-"; 
        }
    }//GEN-LAST:event_optiunea2ActionPerformed

    private void optiunea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optiunea3ActionPerformed
        // TODO add your handling code here:
        if(mult) {
            if(ras[2].equals("-"))
                ras[1] = optiunea3.getText(); 
            else
                ras[2] = "-";
        } else {
            ras[2] = optiunea3.getText(); 
            ras[0] = "-"; 
            ras[1] = "-"; 
        }
    }//GEN-LAST:event_optiunea3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel continutIntrebare;
    private javax.swing.JLabel nrIntrebare;
    private javax.swing.JRadioButton optiunea1;
    private javax.swing.JRadioButton optiunea2;
    private javax.swing.JRadioButton optiunea3;
    private javax.swing.JLabel timerIntrebare;
    private javax.swing.JPanel tipRaspuns;
    // End of variables declaration//GEN-END:variables
}
