/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sie;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;

/**
 *
 * @author denis
 */
public class rezultate extends javax.swing.JFrame {

    /**
     * Creates new form rezultate
     */
    public rezultate() {
        initComponents();
    }
    
    DocumentBuilderFactory factory;
    DocumentBuilder builder;
    Document doc;
    
    String continut = "";
    String raspunsCorect = "";
    String raspunsUtilizator = "";
    String corect = "";
    
    String afisaj = "<html>";
    
    public rezultate(String email){
        initComponents();
        rezultateTestNume.setText("Rezultate test pentru " + email);
        
        factory = DocumentBuilderFactory.newInstance();
        try {
            builder = factory.newDocumentBuilder();
            doc = builder.parse("raspunsuri.xml");
            
            //citirea intrebarilor
            NodeList nrAcces = doc.getElementsByTagName("intrebarea");

            for(int x = 0; x < nrAcces.getLength(); x++) {
                Node nNode = nrAcces.item(x);

                if (nNode.getNodeType() == Node.ELEMENT_NODE) {
                   Element eElement = (Element) nNode;

                    NodeList nList = nNode.getChildNodes();

                    for(int j=0; j < nList.getLength(); j++) {
                        Node node = nList.item(j);
                        if("continut".equals(node.getNodeName())) {
                            continut = node.getTextContent();
                        }                    

                        if("raspunsCorect".equals(node.getNodeName())){
                            raspunsCorect = node.getTextContent();
                        }
                        
                        if("raspunsUtilizator".equals(node.getNodeName())){
                            raspunsUtilizator = node.getTextContent();
                        }
                        
                        if("corect".equals(node.getNodeName())) {
                            corect = node.getTextContent();
                        }
                    }  
                    
                    if(corect.equals("no")){
                        afisaj += "<br/><p>" + continut + "</p><p style=\"color:red\">Raspunsul dat: " + raspunsUtilizator + "</p><p style=\"color:green\">Raspunsul corect: " + raspunsCorect + "</p><br/>";
                    } 
                }  
            }      
            
            afisaj += "</html>";
            rezultateText.setText(afisaj);
            
        } catch (ParserConfigurationException e) {
            e.printStackTrace();
        } catch (SAXException ex) {
            Logger.getLogger(Intrebari.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Intrebari.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rezultateTestNume = new javax.swing.JLabel();
        rezultateText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rezultateTestNume.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rezultateTestNume.setText("Rezultate test");

        rezultateText.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(rezultateText))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(rezultateTestNume)))
                .addContainerGap(352, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rezultateTestNume)
                .addGap(18, 18, 18)
                .addComponent(rezultateText)
                .addContainerGap(369, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rezultate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rezultate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rezultate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rezultate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rezultate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel rezultateTestNume;
    private javax.swing.JLabel rezultateText;
    // End of variables declaration//GEN-END:variables
}
